= APIs

== {sysmlv2} Standard REST APIs

[NOTE]
====
The SysML v2 API is not fully available yet, we are working on it.
For interoperability with {product}, the provided file exchange format is also a solution.
====

{product}'s vision includes a dedicated commitment to interoperability, with a future-oriented perspective on supporting standard APIs for seamless connections with a diverse array of modeling resources.
While the implementation of standard APIs is an aspect under consideration for future development, {product} aims to offer a foundation for fluid collaboration between different tools within the {mbse} - `MBSE` landscape.

As {product} progresses, these future developments in interoperability will further solidify its role as a collaborative platform, fostering an interconnected environment for `MBSE` practitioners.

The ongoing commitment to incorporating standard REST APIs and {sysmlv2} textual specifications underscores {product}'s dedication to providing users with a versatile and interoperable modeling solution.

The whole list of REST APIs is available on the OMG website, in the https://www.omg.org/spec/SystemsModelingAPI/[SystemsModelingAPI section].

[IMPORTANT]
====
All REST APIs start by `/api/rest/`.
====
[IMPORTANT]
====
With the current version of {product}, there is only one commit and branch by project.
The commit ID and branch ID are the same than their project ID.
The API allowing to create a commit do nothing.
====

Below is the list of REST APIs supported in {product}, and a description of key concepts used in REST APIs:

++++
<link rel="stylesheet" href="/_/css/vendor/swagger-ui.css">
<div id="swagger-ui"></div>
<script>
function DisableTryItOutPlugin() {
  // this plugin overrides the Topbar component to return nothing
  return {
    statePlugins: {
      spec: {
        wrapSelectors: {
          allowTryItOutFor: () => () => false
        }
      }
    },
    components: {
      Topbar: function() { return null },
      Servers: function() { return null },
      info: function() { return null }

    }
  }
}

  window.onload = () => {
    window.ui = SwaggerUIBundle({
      url: '../_attachments/sirius-web-openapi.json',
      dom_id: '#swagger-ui',
      deepLinking: false,
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset // Optionnel : permet un rendu standalone
      ],
      plugins: [
        DisableTryItOutPlugin
      ],
      layout: "BaseLayout",
    });
  };
</script>
++++
