= APIs

== {sysmlv2} Standard REST APIs

[NOTE]
====
The SysML v2 API is not fully available yet, we are working on it.
For interoperability with {product}, the provided file exchange format is also a solution.
====

{product}'s vision includes a dedicated commitment to interoperability, with a future-oriented perspective on supporting standard APIs for seamless connections with a diverse array of modeling resources.
While the implementation of standard APIs is an aspect under consideration for future development, {product} aims to offer a foundation for fluid collaboration between different tools within the {mbse} - `MBSE` landscape.

As {product} progresses, these future developments in interoperability will further solidify its role as a collaborative platform, fostering an interconnected environment for `MBSE` practitioners.

The ongoing commitment to incorporating standard REST APIs and {sysmlv2} textual specifications underscores {product}'s dedication to providing users with a versatile and interoperable modeling solution.

The whole list of REST APIs is available on the OMG website, in the https://www.omg.org/spec/SystemsModelingAPI/[SystemsModelingAPI section].

[IMPORTANT]
====
All REST APIs start by `/api/rest/`.
====

Here are some key concepts to know before manipulating the REST APIs in {product}: 

- `Record`: a `Record` represents any data that is consumed (input) or produced (output) by the Systems Modeling API and Services. A `Record` is an abstract concept from which other concrete concepts inherit. A `Record` has the following attributes:
** `id` is the UUID assigned to the `Record`
** `resourceIdentifier` is an URI for the record (*This attribute is not supported in {product}*)
** `alias` is a collection of other identifiers for this record, especially if the record was created or represented in other software applications and systems (*This attribute is not supported in {product}*)
** `humanIdentifier` is a human-friendly unique identifier for this record (*This attribute is not supported in {product}*)
** `description` is a statement that provides details about the record (*This attribute is not supported in {product}*)

- `Project`: a `Project` is a specialized `Record` that represents a container for other `Records` and an entry point for version management and data navigation. The `Project` record has the following attributes:
** `name` is the name of the project.
** `identifiedData` is a derived attribute that is the set of Data Identity records corresponding to the Data contained in the project (*This attribute is not supported in {product}*)
** `commit` is the set of all commits in the `Project` (*This attribute is not supported in {product}*)
** `commitReference` is the set of all commit references in the `Project` (*This attribute is not supported in {product}*)
** `branch` is the set of all the branches in the `Project` and a subset of commitReference (*This attribute is not supported in {product}*)
** `defaultBranch` is the default branch in the `Project` and a subset of branch (*This attribute is not supported in {product}*)
** `tag` is the set of all the tags in the `Project` and a subset of commitReference (*This attribute is not supported in {product}*)
** `usage` is the set of `Project` Usage records representing all other `Projects` being used by the given `Project` (`Project` Usage.usedProject) (*This attribute is not supported in {product}*)
** `queries` is the set of Query records owned by the project. Each Query record represents a saved query for the given project. See Query for details. (*This attribute is not supported in {product}*)
** `created` is the creation timestamp for the project, in ISO8601DateTIme format (*This attribute is not supported in {product}*)

Below is the list of REST APIs supported in {product}:

++++
<link rel="stylesheet" href="/_/css/vendor/swagger-ui.css">
<div id="swagger-ui"></div>
<script>
function DisableTryItOutPlugin() {
  // this plugin overrides the Topbar component to return nothing
  return {
    statePlugins: {
      spec: {
        wrapSelectors: {
          allowTryItOutFor: () => () => false
        }
      }
    },
    components: {
      Topbar: function() { return null },
      Servers: function() { return null },
      info: function() { return null }

    }
  }
}

  window.onload = () => {
    window.ui = SwaggerUIBundle({
      url: '../_attachments/sirius-web-openapi.json',
      dom_id: '#swagger-ui',
      deepLinking: false,
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset // Optionnel : permet un rendu standalone
      ],
      plugins: [
        DisableTryItOutPlugin
      ],
      layout: "BaseLayout",
    });
  };
</script>
++++
