= Troubleshooting

Even the most straightforward installation process can meet unforeseen issues.
This section offers comprehensive troubleshooting tips and solutions to common problems encountered during installation.

If you meet any troubleshooting, please xref:ROOT:help.adoc[contact us] to have solution and to share your troubleshooting to this page.

== Connection refused
If the server fails to start and displays a `Connection refused` error such as:
[source, bash]
----
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: org.postgresql.util.PSQLException: Connection to localhost:5434 refused.
----

Make sure you have a clean database running without any earlier data, and start the server.
You should delete your existing container `docker rm syson-postgres` and even the image `docker rmi image-ID` to ensure a fresh start.

== Changelog not found
If the server fails to start and displays `changelog.xml not found` error such as:
[source, bash]
----
Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: ERROR: The file 'classpath:db/changelog/syson.db.changelog.xml' was not found.
----

Make sure you have included the correct argument to your `java` command according to your {product} version.

TIP: Check that you are consulting the documentation version that matches the JAR version you are trying to run.

Refer to the xref:installation-guide:how-tos/install.adoc#start-app[] section for detailed instructions according to your version.

== Empty page in web browser
If you encounter an empty page while accessing to {product} through your web browser, it might be because you have installed {product} on a local server or machine and want to access it from another one.

If you open the dev tools of your web browser, you may found the following message: `Uncaught TypeError: crypto.randomUUID is not a function`.

In this case, please refer to xref:installation-guide:how-tos/https.adoc[].

== Running docker on Mac Silicon architecture
Docker images are build to run on x86_64 architecture.
If you need to run {product} docker image on a Mac Silicon architecture, please execute the following command in your terminal before executing the docker image:
[source, bash]
----
export DOCKER_DEFAULT_PLATFORM=linux/amd64
----

== Keeping data throughout container recreation
A container looses all internal data when it is recreated from an image.
To keep the database when recreating the container, its files must be stored outside the container.
This is done via mounting a local directory as volume. Add following lines to the database container configuration:
----
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
----

== Problems when not using a standard Docker environment (i.e. docker desktop)
If your container environment is not a standard Docker installation you may run into access problems.
These can be solved by adding
----
    privileged: true
----
to both containers.