= 2025.10.0 (work in progress)

== Key highlights

== Breaking changes

== New features

== Bug fixes

- Fix textual import issues while importing model with `MetadataAccessExpression`.
The following model is now properly imported:

```
private import Metaobjects::SemanticMetadata;

part def Functions {
    attribute x : ScalarValues::String;
}

part functions : Functions [*] nonunique;

metadata def Function :> SemanticMetadata {
    :>> baseType = functions meta SysML::ActionUsage;
}
```
- Fix an issue in the computation of the path of elements in Explorers defined with Sirius Tree APIs instead of Sirius View DSL APIs
This issue was not visible in SysON but could appear in downstream applications defining explorers with the Sirius Tree APIs.

== Improvements

== Dependency update

- Update to https://github.com/spring-projects/spring-boot/releases/tag/v3.5.4[Spring Boot 3.5.4].
- Update to vite 7.1.1 and @vitejs/plugin-react 5.0.0
- Update to vitest 3.2.4 and @vitest/coverage-v8 3.2.4
- Update to @types/node 22.16.0 to match the version of node that we are using

== Technical details

* For technical details on this {product} release (including breaking changes), please refer to https://github.com/eclipse-syson/syson/blob/main/CHANGELOG.adoc[changelog].
