= 2025.10.0 (work in progress)

== Key highlights

- *Standard diagram switching*: in diagrams, it is now possible to switch from one _ViewDefinition_ to another one without having to re-create the diagram.
- *Standard libraries update*: Update standard libraries to SysMLv2 and KerML 2025-07 specification released on July 2025 (see https://github.com/Systems-Modeling/SysML-v2-Release for more details).

== Breaking changes

- In diagrams, (almost) all node descriptions are now synchronized (based on the exposed elements of _ViewUsages_).
This contribution allows to switch from one _ViewDefinition_ to another one in a _ViewUsage_ without having to re-create the diagram.

The following modules have been deleted:

* `syson-diagram-general-view`
* `syson-diagram-interconnection-view`
* `syson-diagram-actionflow-view`
* `syson-diagram-statetransition-view`

New `syson-standard-diagrams-view` module handles all the graphical nodes and edges of the previous modules.

All existing diagrams of these modules are automatically migrated to the remaining `syson-standard-diagrams-view` module.
During this migration, you may lost some graphical nodes and edges that were not handled by the synchronization mechanism.

This contribution introduces some breaking changes:

* `AllocationUsageNodeDescriptionProvider` has been deleted. It is now handled as any other `UsageNodeDescriptionProvider`.
* `UsageNestedActionUsageEdgeDescriptionProvider` has been deleted. It is now handled as any other `UsageNestedUsageEdgeDescriptionProvider`.
* `SynchronizeExposedElementsInputProcessor`, `SynchronizedExposedElementsEventHandler` and `SynchronizedExposedElementsDiagramInput` have been deleted. With the new synchronization mechanism, it is no longer necessary to manually synchronize the exposed elements of a `ViewUsage` with graphical nodes of its associated diagram.
* In `ViewCreateService`
** `getDiagramEmptyCandidate` has been deleted
* In `ViewEdgeService`
** `getAllReachableAllocationUsages` has been deleted
* In `ViewNodeService`
** `getAllReferencingPerformActionUsages` has been deleted
** `getAllReachableActors` has been deleted
* In `ViewToolService`
** `addExistingElements` has been deleted and replaced by `addToExposedElements`
** `createTransitionUsage` has been moved to `ViewCreateService`
** `createViewInFreeFormCompartment` has been deleted
* In `ToolService`
** `updateExposedElements` has been deleted and replaced by `ViewToolService#expose`
* `NodeCreationTester` has been renamed to `ToolTester`

== New features

- In diagrams, it is now possible to switch from one _ViewDefinition_ to another one without having to re-create the diagram.


== Bug fixes

- Fix textual import issues while importing model with `MetadataAccessExpression`.
The following model is now properly imported:

```
private import Metaobjects::SemanticMetadata;

part def Functions {
    attribute x : ScalarValues::String;
}

part functions : Functions [*] nonunique;

metadata def Function :> SemanticMetadata {
    :>> baseType = functions meta SysML::ActionUsage;
}
```
- Fix an issue in the computation of the path of elements in Explorers defined with Sirius Tree APIs instead of Sirius View DSL APIs
This issue was not visible in SysON but could appear in downstream applications defining explorers with the Sirius Tree APIs.

- Fix action "New objects from text" being available on all semantic elements in the _Explorer_ view.
Now it is only available on SysML model elements.
- Fix library update performance and ensure it does not impact standard libraries.

== Improvements

- Update the PostgreSQL version used in the docker image (used for tests purposes) to 15.
If you are using the docker image and want to upgrade to PostgreSQL 15, please refer to xref:installation-guide:migration-process.adoc[the migration process page of the official documentation].
Also please remember only YEAR.MONTH.0 versions are stable and suitable for production deployments.
Other versions, such as intermediate releases, are intended solely for testing purposes.
- Update standard libraries to SysMLv2 and KerML 2025-07 specification released on July 2025 (see https://github.com/Systems-Modeling/SysML-v2-Release for more details).

== Dependency update

- Update to https://github.com/eclipse-sirius/sirius-web[Sirius Web 2025.8.3]
- Update to https://github.com/spring-projects/spring-boot/releases/tag/v3.5.4[Spring Boot 3.5.4]
- Update to vite 7.1.1 and @vitejs/plugin-react 5.0.0
- Update to vitest 3.2.4 and @vitest/coverage-v8 3.2.4
- Update to @types/node 22.16.0 to match the version of node that we are using

== Technical details

* For technical details on this {product} release (including breaking changes), please refer to https://github.com/eclipse-syson/syson/blob/main/CHANGELOG.adoc[changelog].
