= 2026.3.0 (work in progress)

== Key highlights

== New features

* SysON can now be connected with Elasticsearch to support cross-project search.
The Elasticsearch integration uses its own indexing logic instead of the default one provided by Sirius Web.
This allows to keep indices compact, and ensures information stored in the indices are useful to perform cross-project search.
You can find more information on how to setup Elasticsearch, how elements are mapped to index documents, and how to query them in the documentation.
+
This feature is currently considered experimental.
Try it out and give feedback by reporting bugs and suggesting new features.
It's not recommended for production use.

== Bug fixes

* In diagrams:

** Fix an issue where some type of `Elements` could appear in the wrong compartment if they shared a common type with said compartment, for example `ViewUsage` elements could appear in the _parts_ compartment since they extends `PartUsage`.

* In textual import/export:

** Fix the textual export of `OccurrenceUsage` to avoid duplication of the _abstract_ keyword.
** Fix the textual export to properly escape names used in qualified names in some references.
** Fix an error during textual export where `Expose` elements with apostrophes in their name were not properly escaped.
** Fix the textual import to properly resolve the _payload_ argument of a `SendActionUsage` used in a `TransitionUsage`.
The following model is now properly imported:
+
```
package Package1 {
    attribute def Sig ;
    part p;

    state state1 {
        state s2;
        state s3;
        transition T1
              first s2
              accept s : Sig via p
              do send s to p // s failed to resolve here before
              then s3;
    }
}
```

** Fix the textual import to properly resolve unnamed redefined `Feature` in a `FeatureChain`.
The following model is now properly imported:
+
```
part system {
	part def Logical {
		part component {
			part component2;
		}
	}
	part l : Logical {
		part :>> component;
	}
	part c2  = l.component.component2; // "component" now resolves to "p1::l::component" instead of "p1::Logical::component"
}
```

* In _Details_ view:

** `Req Id` and `Declared Short Name` properties of `RequirementDefinition` and `RequirementUsage` are now synchronized, as required by the SysMLv2 specification.

== Improvements

* In diagrams:

** When dropping `Element` from the _Explorer_ view to a diagram, hide its compartments unless it's the _interconnection compartment_ on an _Interconnection View_ diagram.
** When dropping `Element` from the _Explorer_ view to a diagram, if the element was already visible on the diagram, a warning is displayed to indicate it.
** Add _ends_ compartments on `AllocationDefinition` graphical nodes.
** Add _attributes_, _ends_, _doc_ and _parts_ compartments on `ConnectionDefinition` graphical nodes.
** Add _parts_ compartments on `PartDefinition`, `AllocationDefinition` and `InterfaceDefinition` graphical nodes.
** Add _actors_ compartment on `RequirementUsage` and `RequirementDefinition` graphical nodes.
** Add _Subjects_ as graphical nodes in addition to the existing the _subject_ compartment for `CaseUsages`, `CaseDefinitions`, `UseCaseUsage`, `UseCaseDefinitions`,  `RequirementsUsages`, `RequirementsDefinitions` and `SatisfyRequirementUsages`.
** The graphical edge tools _Become nested Attribute_ is now available on `AttributeUsage` graphical nodes when the targeted graphical node is a `Usage` or `Definition`.
** The graphical edge tools _Add as nested Attribute_ is now available on all `Usage` and `Definition` graphical nodes that target an `AttributeUsage` graphical node.
** Add _New Satisfy_ tool on `RequirementUsage` graphical nodes.
This tool allows to create a `SatisfyRequirementUsage` based on the `RequirementUsage` selected during the tool creation.
** Add _New Satisfy Requirement_ graphical edge tool between `Feature` graphical nodes and `RequirementUsage` graphical nodes.
This tool allows to create a `SatisfyRequirementUsage` between the `Feature` and `RequirementUsage` selected during the tool creation.
** Add the  _timeslice_ and _snapshot_ prefixes in the label of `OccurrenceUsage` graphical nodes and some of the graphical nodes representing subclasses of `OccurrenceUsage`.
** Newly created `AllocationDefinition` and `ConnectionDefinition` graphical nodes now have two initial _connection ends_, named _source_ and _target_.
Additional ends can be created using the _New end_ graphical node tool (which replaces the _New Part as end_ previously available only on `AllocationDefinition` graphical nodes).
** Newly created `InterfaceDefinition` graphical nodes now have two initial _ports_ named _source_ and _target_.
Additional ports can be created using the _New Port as end_ graphical node tool.
** Allow to edit the _timeslice_ and _snapshot_ property of `OccurrenceUsage` and subtypes graphical nodes with the direct edit.

* In textual import/export:

** Implement the textual export for `StateUsage` and `StateDefinition`.
** Implement the textual export for `TransitionUsage`.
** Implement the textual export for `ExhibitStateUsage` such as in:
+
```
package root {
    part part1 {
        exhibit state s1 {
            /* doc */
        }
    }
    part part2 {
        exhibit part1.s1 {
            /* doc */
        }
    }
}
```
** Implement the textual export for `AllocationUsage` and `AllocationDefinition`.

* In _Details_ view:

** `Req Id` property of `RequirementDefinition` is now visible in the _Core_ tab of the _Details_ view.

* Miscellaneous:

** Add support for publishing representations with libraries.
Publishing a project that contains representations now produces libraries that also contain the representations.
Users can navigate to `/libraries/<library identifier>` to open a library and see its representations.

== Technical details

* For technical details on this {product} release (including breaking changes), please refer to https://github.com/eclipse-syson/syson/blob/main/CHANGELOG.adoc[changelog].
