= 2026.5.0 (work in progress)

== Key highlights

== Breaking changes

- As of version 2026.5.0, SysON now requires **Java 21** or later.

== New features

== Bug fixes

* In diagrams:

** In _Interconnection View_ diagrams, fix an issue where the `parts` compartment of `PartDefinition` graphical node was incorrectly revealed when creating a `PartUsage` from the `PartDefinition` graphical node, even if the `interconnection` compartment was already visible.

* In _Details_ view:

** Fix an issue that allowed to edit library objects via the _Details_ view. 

== Improvements

* In diagrams:

** Add tools to create timeslices and snapshots, available on `OccurrenceUsage`, `ItemUsage`, and `PartUsage` graphical nodes.
These tools leverage a selection dialog to either create a specific timeslice/snapshot graphical node or, if no selection is made, default to a timeslice/snapshot `OccurrenceUsage` graphical node.

== Technical details

* For technical details on this {product} release (including breaking changes), please refer to https://github.com/eclipse-syson/syson/blob/main/CHANGELOG.adoc[changelog].
