= 2026.11.0 (work in progress)

== Key highlights

== New features

* In diagrams:

** `New Reference` tools have a selection dialog.
This allows to select an `Element` that the new `ReferenceUsage` uses.
If the selected element is a `Classifier` (e.g `PartDefinition`), it is used to type the new `ReferenceUsage`.
It it is a `Feature` then the new `ReferenceUsage` references this given feature.
The tools are also able to create an empty `ReferenceUsage`.

== Bug fixes

* In diagrams:

** Fix available diagram tools on standard diagrams created on a root `Namespace`.

* In textual import/export:

** Report syntax errors that may leave an uploaded SysML file partially imported.
The parsed elements are still imported, and the loading report identifies the syntax problem and warns about possibly missing elements.

== Improvements

== Technical details

* For technical details on this {product} release, including breaking changes, please refer to the https://github.com/eclipse-syson/syson/blob/main/CHANGELOG.adoc[changelog].
