= 2026.11.0 (work in progress)

== Key highlights

* _General View_ diagrams now provide an action to add existing connected elements in both directions.

== New features

* In diagrams:

** `New Reference` tools have a selection dialog.
This allows to select an `Element` that the new `ReferenceUsage` uses.
If the selected element is a `Classifier` (e.g `PartDefinition`), it is used to type the new `ReferenceUsage`.
It it is a `Feature` then the new `ReferenceUsage` references this given feature.
The tools are also able to create an empty `ReferenceUsage`.

** Add the _Add existing connected elements_ action in the _Related Elements_ context menu section.
The action adds existing project elements connected to the selected element through inbound or outbound relationships and displays the corresponding edges when possible.

== Bug fixes

* In diagrams:

** Fix available diagram tools on standard diagrams created on a root `Namespace`.

== Improvements

== Technical details

* For technical details on this {product} release, including breaking changes, please refer to the https://github.com/eclipse-syson/syson/blob/main/CHANGELOG.adoc[changelog].
