= 2026.3.0 (work in progress)

== Key highlights

== New features

* SysON can now be connected with Elasticsearch to support cross-project search.
The Elasticsearch integration uses its own indexing logic instead of the default one provided by Sirius Web.
This allows to keep indices compact, and ensures information stored in the indices are useful to perform cross-project search.
You can find more information on how to setup Elasticsearch, how elements are mapped to index documents, and how to query them in the documentation.
+
This feature is currently considered experimental.
Try it out and give feedback by reporting bugs and suggesting new features.
It's not recommended for production use.

== Bug fixes

* In textual import/export:

** Fix the textual export of `OccurrenceUsage` to avoid duplication of the _abstract_ keyword.
** Fix the textual export to properly escape names used in qualified names in some references.
** Fix the textual import to properly resolve the _payload_ argument of a `SendActionUsage` used in a `TransitionUsage`.
The following model is now properly imported:
+
```
package Package1 {
    attribute def Sig ;
    part p;

    state state1 {
        state s2;
        state s3;
        transition T1
              first s2
              accept s : Sig via p
              do send s to p // s failed to resolve here before
              then s3;
    }
}
```

== Improvements

* In diagrams:

** When dropping `Element` from the _Explorer_ view to a diagram, hide its compartments unless it's the _interconnection compartment_ on an _Interconnection View_ diagram.
** Add _attributes_, _doc_ and _parts_ compartments on `ConnectionDefinition` graphical nodes.
** Add _parts_ compartments on `PartDefinition`, `AllocationDefinition` and `InterfaceDefinition` graphical nodes.
** Add _actors_ compartment on `RequirementUsage` and `RequirementDefinition` graphical nodes.
** Add _Subjects_ as graphical nodes in addition to the existing the _subject_ compartment for `CaseUsages`, `CaseDefinitions`, `UseCaseUsage`, `UseCaseDefinitions`,  `RequirementsUsages`, `RequirementsDefinitions` and `SatisfyRequirementUsages`.
** The graphical edge tools _Become nested Attribute_ is now available on `AttributeUsage` graphical nodes when the targeted graphical node is a `Usage` or `Definition`.
** The graphical edge tools _Add as nested Attribute_ is now available on all `Usage` and `Definition` graphical nodes that target an `AttributeUsage` graphical node.


* In textual import/export:

** Implement the textual export for `StateUsage` and `StateDefinition`.
** Implement the textual export for `TransitionUsage`.
** Implement the textual export for `ExhibitStateUsage` such as in:
+
```
package root {
    part part1 {
        exhibit state s1 {
            /* doc */
        }
    }
    part part2 {
        exhibit part1.s1 {
            /* doc */
        }
    }
}
```
* Add support for publishing representations with libraries.
Publishing a project that contains representations now produces libraries that also contain the representations.
Users can navigate to `/libraries/<library identifier>` to open a library and see its representations.

== Technical details

* For technical details on this {product} release (including breaking changes), please refer to https://github.com/eclipse-syson/syson/blob/main/CHANGELOG.adoc[changelog].
