= API details

The complete list of {sysmlv2} REST APIs is available on the https://www.omg.org/spec/SystemsModelingAPI/[OMG website].


[IMPORTANT]
====
*Endpoint Prefix*: All REST APIs in {product} start with `/api/rest/`.
====

[IMPORTANT]
====
In {product}, each project uses a single commit and branch by default.
The commit ID and branch ID are same to the project ID.
The API for creating additional commits isn't functional in the current implementation.
====

[TIP]
====
To test the API on your local server, navigate to:
http://localhost:8080/swagger-ui/index.html

This URL opens the Swagger UI, an interactive documentation tool for APIs.
The interface provides an overview of API endpoints, supports testing with input parameters, and displays responses for better understanding.
====

== Supported REST APIs in {product}

Below is the list of REST APIs supported in {product}, along with descriptions of key concepts used in REST APIs:

++++
<link rel="stylesheet" href="/_/css/vendor/swagger-ui.css">
<div id="swagger-ui"></div>
<script>
function DisableTryItOutPlugin() {
  // this plugin overrides the Topbar component to return nothing
  return {
    statePlugins: {
      spec: {
        wrapSelectors: {
          allowTryItOutFor: () => () => false
        }
      }
    },
    components: {
      Topbar: function() { return null },
      Servers: function() { return null },
      info: function() { return null }

    }
  }
}

  window.onload = () => {
    window.ui = SwaggerUIBundle({
      url: './../_attachments/sirius-web-openapi.json',
      dom_id: '#swagger-ui',
      deepLinking: false,
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset // Optional : allow a standalone rendering
      ],
      plugins: [
        DisableTryItOutPlugin
      ],
      layout: "BaseLayout",
    });
  };
</script>
++++
