= APIs

== {sysmlv2} Standard REST APIs

[NOTE]
====
The {sysmlv2} API isn't fully available yet, but we're actively developing it.
In the meantime, you can use the provided file exchange format to ensure interoperability with {product}.
====

{product} focuses on enabling seamless collaboration within the {mbse} - `MBSE` ecosystem.
With a strong emphasis on interoperability, {product} aims to support future standard APIs that will connect to a wide range of modeling tools and resources.

Although we've set standard API implementation as a key development goal, {product} already provides a solid foundation for effective collaboration between tools, reinforcing its role as a powerful platform for MBSE practitioners.


{product}’s commitment to incorporating standard REST APIs and {sysmlv2} textual specifications highlights its dedication to delivering a flexible and interoperable modeling solution.

Refer to the xref:developer-guide:api/api-details.adoc[API Details Section] for more information about the supported APIs.

== APIs Cookbook

For detailed examples, best practices, and guidance on using {product}’s REST APIs, consult the xref:developer-guide:api/api-cookbook.adoc[APIs Cookbook].
The cookbook includes:

* Step-by-step guides for common tasks.
* Code snippets for API interactions.
* Explanations of core API concepts.