= Local installation of {product} for multi-user testing purposes

This section provides instructions for installing a multi-user version of the application, intended for testing in an environment with multiple users. This setup includes configurations to allow access by different users within the same local network but does not apply any specific security configurations.

To be used by multiples users, the {product} serveur must be availlable using the network to all users.
The require to have HTTPS configured on the {product} serveur.


== Prepare single user deployment

This procedure is an extantion of the basic installation procedure xref:installation-guide:how-tos/install/local_test.adoc[single user]

== Prepare certificates

Detailed instructions to generate SSL certificates are explained xref:installation-guide:how-tos/https.adoc[here]

== Share the {product} server access

By following the two previous procedure, the {product} server is now availlable on the network, hosted by your local computer and secured using a self-signed HTTPS certificate.

To share the server acces with other people on the same network, the IP adrress of the local computer must be share.

The {product} server must be availlable ont the url https://<localComputerIp>:8080/[]


[WARNING]
====
Some enterprise networks can be secured or configured to block this kind of traffic
====


If you encounter any issues during the installation process, please refer to the xref:troubleshooting.adoc[troubleshooting guide] for detailed solutions.
