= ADR-002 - Services organization

== Context

In SysON, we have a lot of services that are used in different places.
Some services query the model, some other services modify the model.
Some services query the diagram/table, some other services modify the diagram/table.
Some services are a mix of both querying/modifying.
Some services are called by AQL expressions, some other services are called by Java code.
Some services classes are spring @Service, some other services classes are not.

With many contributors since the beginning of the project, and not a clear and precise guide on how to add new services, the services are not always in the right place, and there are many services classes everywhere in the code base.

All those points make it difficult to find a service, to know where to add a new service, to know where to find a service that does something similar to what we want to do.

== Decision

At this point, we need to organize all these services in a more logical way.
The decision is to create a clear organization of the services in packages and classes.
The main idea is to have services grouped by their purpose and usage.

- Services that query/mutate the model will be located in the new module `syson-sysml-metamodel-services`.
 - this module will depend on `syson-sysml-metamodel`.
 - all services in this module won't depend on Sirius-Web or any diagram/table related code.
- Services that query/mutate the model through Sirius-Web services will be located in the existing module `syson-services`.
  - all services in this module will be allowed to depend on Sirius-Web
  - for example, services that query the model through `IObjectSearchService`.
- Services that query/mutate a diagram will be located in the new module `syson-diagram-services`.
 - all services in this module will be allowed to depend on Sirius-Web.
- Services that query/mutate a table will be located in the new module `syson-table-services`.
 - all services in this module will be allowed to depend on Sirius-Web.
- Services that query/mutate a tree will be located in the new module `syson-tree-services`.
 - all services in this module will be allowed to depend on Sirius-Web.
- Services that query/mutate a form will be located in the new module `syson-form-services`.
 - all services in this module will be allowed to depend on Sirius-Web.
- Services that query/mutate a form will be located in the new module `syson-representation-services`.
 - all services in this module will be allowed to depend on Sirius-Web.
 - will contain services that can be used in all representations

- Services will be grouped in classes by their purpose and usage.
 - a service that query the model will be in a class named `SomethingQueryService`.
 - a service that mutate the model will be in a class named `SomethingMutationService`.
 - a service that query the diagram will be in a class named `SomethingDiagramQueryService`.
 - a service that mutate the diagram will be in a class named `SomethingDiagramMutationService`.
 - a service querying label of elements will be in a class named `LabelQueryService`.
 - a service modifying the label of elements will be in a class named `LabelMutationService`.
 - a service querying label of diagram elements will be in a class named `LabelDiagramQueryService`.
 - a service modifying the label of elements will be in a class named `LabelDiagramMutationService`.


- The initial categories of services will be:
 - `syson-sysml-metamodel-services`
  - Usage
  - Definition
  - Any other category needed in the future like Part, Action...
 - `syson-services`
  - Label
  - DirectEdit
  - Create
  - Delete
  - Move
  - DragAndDrop
 - `syson-diagram-services`
  - Node
  - Edge
  - BorderNode
  - Compartment
- `syson-table-services`
  - Row
  - Column
  - Cell
- `syson-tree-services`
  - Tree
  - TreeItem
- `syson-form-services`
  - Widget
- `syson-representation-services`
  - Expose

== Consequences

A lot of services will be moved from their current location to the new ones.
The breaking changes section of the changelog will be updated to inform users of these changes.
All new services will have to follow this organization.

== Status

Redaction of this ADR in progress.
