= Keyboard shortcuts

include::user-manual:partial$before-you-start-experimental-all.adoc[]

== General

To delete an element, select it and press the `Del` key in the representation editor.

== Navigation

In a diagram, users can press Alt and drag with the mouse to browse the diagram without moving any elements.
This is useful for large diagrams where elements might appear in the background when the view is zoomed out.

== Selection

In a diagram, users can left-click on an element to select it without displaying the contextual palette on the node (right-click to display the palette).

== Basic editing

Users can press the `F2` key or start typing the new value directly to update an element name in the representation editor.

Explore further by referring to the following how-tos for xref:user-manual:features/general-view.adoc#edit-label[Edit Label action].

== Multi-selection

Two ways to select several elements exist:

=== Ctrl key

Users can select an element by clicking it and then select another one by holding the `Ctrl` key while clicking the other element.
This keyboard shortcut is available in the representation editor and in the {explorer} view.

=== Shift key

To select several elements at once in the representation editor, hold the `Shift` key and draw a rectangular area around the elements to select.
After releasing the mouse button, all elements in the area are selected.

== Search

Users can display the filter bar by pressing `Ctrl+f` (Windows/Linux) or `Cmd+f` (macOS) in the {explorer} view.

Explore further by referring to the following how-tos for xref:hands-on/how-tos/explorer.adoc#explorer-filter[Filter elements].
