= Keyboard shortcuts

include::user-manual:partial$before-you-start-os-experimental-all.adoc[]

== General

To delete a given element, user can select the element and the press the `Del` key from representation editor.

== Basic editing

User can press `F2` key or start typing the new value directly to efficiently update an element name from representation editor.

Explore further by referring to the following how-tos for xref:user-manual:features/general-view.adoc#edit-label[Edit Label action].

== Multi-selection

Two ways to select several elements exist:

=== Ctrl key

A user can select an element by clicking on it and then select another one by holding `Ctrl` key and clicking on the other element.
This keyboard shortcut is available in the representation editor and in the {explorer} view.

=== Shift key

To select several element in one action from representation editor, user can press `Shift` key and draw a rectangular area around elements that user wants to select.
After releasing the click, all element in the area are selected.

== Search

User can display the filter bar by holding `Ctrl+f` (Windows/Linux) or `Cmd+f` (MacOS) from the {explorer} view.

Explore further by referring to the following how-tos for xref:hands-on/how-tos/explorer.adoc#explorer-filter[Filter elements].