= Configuring HTTPS for local server deployment of {product} for testing purposes

[WARNING]
====
Enabling HTTPS with a self-signed certificate is intended for testing purposes only and shouldn't be used in a production environment.
Self-signed certificates don't provide the same level of security and trust as certificates issued by a trusted Certificate Authority (CA).
For production deployments, obtain a valid certificate from a trusted CA to ensure secure and reliable communication.
====

If you intend to install {product} on a local server or machine and allow several users to access it, you must enable HTTPS.
If you don't have a certificate, you can generate one by using https://docs.oracle.com/en/java/javase/11/tools/keytool.html[keytool] for testing purposes only.

This procedure requires to have the `keytool` application to be installed (the application comes with the Java Runtime Environment as explain in xref:requirements.adoc[prerequisites]:)

. Create a self-signed certificate:
+
[source, bash]
----
keytool -genkeypair -alias myalias -keyalg RSA -keysize 2048 -validity 365 -keystore keystore.jks
----
. If you have installed {product} with xref:installation-guide:how-tos/install.adoc#docker-install[docker], just update your docker-compose file as below (otherwise, please go to next instruction): 
+
[source, bash]
----
version: "3.8"
services:
  database:
    ... no need to change anything in the database section
  app:
    ... just add the following configuration in the app section
    volumes:
      - ./keystore.jks:/keystore.jks
    entrypoint:
      - java
      - -jar
      - /syson-application.jar
      - --server.ssl.key-store=./keystore.jks
      - --server.ssl.key-store-password=PASSWORD_USED_IN_STEP_1
      - --server.ssl.key-store-type=JKS
      - --server.ssl.key-alias=myalias
      - --server.ssl.key-password=PASSWORD_USED_IN_STEP_1
networks:
  ... no need to change anything in the networks section
---- 

. If you have installed {product} manually, place the certificate file next to your `{product}-application` JAR file
. Launch your JAR (as explained in the xref:installation-guide:how-tos/install.adoc#start-app[start the application section] with the following extra properties:
+
[source, bash]
----
  --server.ssl.key-store=./keystore.jks \
  --server.ssl.key-store-password=PASSWORD_USED_IN_STEP_1 \
  --server.ssl.key-store-type=JKS \
  --server.ssl.key-alias=myalias \
  --server.ssl.key-password=PASSWORD_USED_IN_STEP_1
----
. Every user in your local network can now access the application at:
`https://{product}_SERVER_IP:8080`